UPDATE "GrassSpecies"
SET
  "idealTempMin" = 70,
  "idealTempMax" = 95,
  "idealRainfallMin" = 20,
  "idealRainfallMax" = 60,
  "idealHardinessZone" = '7-10',
  "idealKoppenZone" = 'Cfa, BSh, Cwa',
  "idealSpringTempMin" = 60,
  "idealSpringTempMax" = 85,
  "idealSummerTempMin" = 75,
  "idealSummerTempMax" = 100,
  "idealFallTempMin" = 60,
  "idealFallTempMax" = 85,
  "idealWinterTempMin" = 30,
  "idealWinterTempMax" = 55,
  "idealSpringRainfallMin" = 1,
  "idealSpringRainfallMax" = 5,
  "idealSummerRainfallMin" = 1,
  "idealSummerRainfallMax" = 5,
  "idealFallRainfallMin" = 1,
  "idealFallRainfallMax" = 5,
  "idealWinterRainfallMin" = 1,
  "idealWinterRainfallMax" = 5,
  "minGrowingDays" = 100,
  "idealEcoregion" = 'Tropical and Subtropical Grasslands, Temperate Grasslands, Southeastern USA Plains'
WHERE name = 'Bermuda Grass';
